version: 2.1

commands:
  e2e:
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Create .env file from env vars
          command: printenv >> ./.env
      - run:
          name: Reset the test site
          command: |
            echo "Resetting the test site"
            apt-get update
            apt-get install sshpass
            mkdir -p /root/.ssh
            echo "$SSH_KNOWN_HOST" > /root/.ssh/known_hosts
            sshpass -p "$SSH_USER_PASS" scp ./e2e-plugin.php $SSH_USER@$SSH_HOST:/htdocs/wp-content/plugins/
            sshpass -p "$SSH_USER_PASS" ssh -v $SSH_USER@$SSH_HOST 'bash -s' < ./e2e-reset.sh
      - run:
          name: Run tests
          command: |
            npm install
            npx playwright install chromium
            npm run test
      - store_artifacts:
          path: playwright-report
      - store_artifacts:
          path: test-results
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config user.name "$GIT_COMMITTER_NAME"
            git config user.email "$GITHUB_COMMITER_EMAIL"
            git checkout -b gh-pages
            mv playwright-report docs
            cd docs
            git add --all
            git commit -m "Deploy Playwright Report [skip ci]"
            git push "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" --force
      - run:
          name: Notify about failure
          command: |
            CURRENT_GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
            if [[ "$CURRENT_GIT_BRANCH" == "trunk" ]]; then
              curl \
                --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"⚠️ E2E tests have failed. Check <$CIRCLE_BUILD_URL|the artifacts> to verify.\"}}]}" \
                -H "Content-type: application/json" \
                -H "Authorization: Bearer $SLACK_AUTH_TOKEN" \
                -X POST https://slack.com/api/chat.postMessage
            fi
          when: on_fail

executors:
  docker-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.42.0-jammy

jobs:
  main:
    executor: docker-playwright
    steps:
      - e2e

workflows:
  version: 2
  test-main:
    jobs:
      - main
  test-main-scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5" # Weekdays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - trunk
    jobs:
      - main
