version: 2.1

executors:
  docker-wordpress:
    docker:
      - image: cimg/php:7.4-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress

commands:
  e2e:
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Create .env file from env vars
          command: printenv > ./scripts/.env
      - run:
          name: Setup local SSL
          command: sudo ./scripts/ssl.sh
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Installing necessary dependencies
          command: |
            sudo apt-get update --allow-releaseinfo-change
            sudo apt-get install -y default-mysql-client
            sudo apt-get install -y libgbm-dev
            sudo apt-get install -y php-mysqli
            sudo apt-get install -y jq
      - run:
          name: Run stunnel for local HTTPS
          command: |
            sudo apt-get install -y stunnel
            sudo stunnel ./docker/stunnel.conf
          background: true
      - run:
          name: Installing wp-cli
          command: sudo ./scripts/install-wp-cli.sh
      - run:
          name: Download WordPress
          command: wp core download --allow-root
      - run:
          name: Configure WordPress
          command: wp core config --allow-root --dbname=wordpress --dbuser=wordpress --dbhost=127.0.0.1 --dbpass=wordpress
      - run:
          name: Setup WP & plugins
          command: sudo ./scripts/setup.sh
      - run:
          name: Launch server
          command: wp server --host=newspack-e2e.com --port=8000 --allow-root
          background: true
      - run:
          name: Waiting for server to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 8000 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for server && exit 1
      - run:
          name: Installing node dependencies
          command: npm ci
      - run:
          name: E2E Tests with Cypress
          command: npm run test:visual:check
      - run:
          name: Notify about failure
          command: |
            curl \
              --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"⚠️ E2E tests have failed for channel: \`$CIRCLE_JOB\`. Check <$CIRCLE_BUILD_URL|the test recordings> to verify.\"}}]}" \
              -H "Content-type: application/json" \
              -H "Authorization: Bearer $SLACK_AUTH_TOKEN" \
              -X POST https://slack.com/api/chat.postMessage
          when: on_fail
      - store_artifacts:
          path: artifacts
      - store_artifacts:
          path: cypress/snapshots

jobs:
  stable:
    executor: docker-wordpress
    environment:
      TEST_CHANNEL: stable
    steps:
      - e2e
  alpha:
    executor: docker-wordpress
    environment:
      TEST_CHANNEL: alpha
    steps:
      - e2e
  master:
    executor: docker-wordpress
    environment:
      TEST_CHANNEL: master
    steps:
      - e2e

workflows:
  version: 2
  test-stable-scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 3" # Wednesdays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - master
    jobs:
      - stable
  test-alpha-scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 5" # Fridays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - master
    jobs:
      - alpha
  test-master-scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5" # Weekdays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - master
    jobs:
      - master

  test-stable:
    jobs:
      - stable
  test-alpha:
    jobs:
      - alpha
  test-master:
    jobs:
      - master
