version: 2.1

executors:
  docker-wordpress:
    docker:
      - image: cimg/php:7.4-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress

commands:
  e2e:
    parameters:
      channel:
        default: 'stable'
        type: string
    environment:
      TEST_CHANNEL: <<parameters.channel>>
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install necessary dependencies
          command: |
            sudo apt-get update --allow-releaseinfo-change
            sudo apt-get install -y default-mysql-client
            sudo apt-get install -y libgbm-dev
            sudo apt-get install -y php-mysqli
            sudo apt-get install -y jq
      - run:
          name: Install wp-cli
          command: sudo ./scripts/install-wp-cli.sh
      - run:
          name: Download WordPress
          command: wp core download --allow-root
      - run:
          name: Configure WordPress
          command: wp core config --allow-root --dbname=wordpress --dbuser=wordpress --dbhost=127.0.0.1 --dbpass=wordpress
      - run:
          name: Setup WP & plugins
          command: sudo ./scripts/setup.sh
      - run:
          name: Launch server
          command: wp server --port=8000 --allow-root
          background: true
      - run:
          name: Waiting for server to be ready
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 8000 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for server && exit 1
      - run:
          name: Install node dependencies
          command: npm ci
      - run:
          name: E2E Tests with Cypress
          command: npm run test:ci
      - store_artifacts:
          path: artifacts
      - store_artifacts:
          path: cypress/snapshots

jobs:
  e2e-stable:
    executor: docker-wordpress
    steps:
      - e2e:
        channel: 'stable'
  e2e-alpha:
    executor: docker-wordpress
    steps:
      - e2e:
        channel: 'alpha'
  e2e-master:
    executor: docker-wordpress
    steps:
      - e2e:
        channel: 'master'

workflows:
  version: 2
  test-stable:
    triggers:
      - schedule:
          cron: "0 7 * * 4" # Thursdays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e-stable
  test-alpha:
    triggers:
      - schedule:
          cron: "0 7 * * 1" # Mondays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e-alpha
  test-master:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5" # Weekdays at 7am UTC / 2am EST / 11pm PST
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e-master
